# Decision tree classifier for hosts classification

We are going to perform classification of hosts using DTs classifier

### Imports

In [1]:
import numpy as np
import pandas as pd

### Import dataset

We have a preprocessed pandas dataframe consisting of anonymized host behaviour. Each host belongs to a certain **unit** within the subnet.

In [2]:
df = pd.read_pickle('balanced_preprocessed_dataset.pkl')
df.head()

          mean                                                              \
  FlowDuration
            00        01        02        03        04        05        06
0    -0.007622 -0.006103 -0.009019 -0.006422 -0.012099 -0.007141 -0.007069
1    -0.009677 -0.011074 -0.010790 -0.008082 -0.013610 -0.009863 -0.009743
2    -0.009484 -0.010427 -0.010896 -0.008080 -0.013609 -0.009918 -0.009838
3    -0.009932 -0.011126 -0.010762 -0.007984 -0.013595 -0.009918 -0.009470
4    -0.007484 -0.005790 -0.008930 -0.006322 -0.012029 -0.007007 -0.006911

                                     ...            max                      \
                                     ...          Bytes
         07        08        09      ...             19        20        21
0 -0.012616 -0.009572 -0.011851      ...      -0.015290 -0.014971 -0.016604
1 -0.014340 -0.011510 -0.014119      ...      -0.015291 -0.014971 -0.016604
2 -0.014320 -0.011545 -0.013922      ...      -0.015291 -0.014971 -0.016604
3 -0.014341 -0.011979 -0.014230      ...      -0.015291 -0.014971 -0.016604
4 -0.012538 -0.009441 -0.011706      ...      -0.015274 -0.014955 -0.016588

                               Label  \
                               Label
         22        23 anon_net_range
0 -0.016766 -0.016320             28
1 -0.016766 -0.016320             28
2 -0.016766 -0.016320             28
3 -0.016766 -0.016320             28
4 -0.016752 -0.016307             26

                                                              \

                                          addr_range    unit
0  ef160f55b36bd48b37f22bc9c48819b1a0259c2dd27ccc...  CEITEC
1  93b8f5a052053b0db4731b671f78b8c5e5817d38d51ba9...  CEITEC
2  ac600c8985d0f198d532737ea9d58db00905c6c6bebb6b...  CEITEC
3  48bab257d30b1c6eaa225275fe60fc5e1dfe61afe54ace...  CEITEC
4  1cd00c373ace404b829e822bf076631b564bf2bc70db82...  CEITEC

                                                     Unit_encoding

                                             subunit
0   frontendy diskovych poli a aplikacni servery ...             0
1   frontendy diskovych poli a aplikacni servery ...             0
2   frontendy diskovych poli a aplikacni servery ...             0
3   frontendy diskovych poli a aplikacni servery ...             0
4                                                CRS             0

[5 rows x 653 columns]

In [3]:
df['Label', 'Label', 'unit'].unique()

array(['CEITEC', 'CESNET', 'CTT', 'ESF', 'FF', 'FI', 'FIeduroamnaFI',
       'FNBrno', 'FSS', 'FSpS', 'IBA', 'LF', 'PedF', 'PravF', 'PrirF',
       'RMU', 'SKM', 'Teiresias', 'Telc', 'UKB', 'UVT', 'VPN'],
      dtype=object)

In [4]:
df['Label', 'Label', 'unit'].value_counts()

UVT              3500
SKM              3246
PrirF            2599
CEITEC           2223
LF               1475
FI               1289
FF               1089
FIeduroamnaFI    1020
FSS               802
PedF              740
UKB               649
ESF               554
PravF             536
RMU               429
FSpS              410
Teiresias         130
Telc               99
IBA                96
VPN                83
CTT                19
FNBrno              7
CESNET              3
Name: (Label, Label, unit), dtype: int64

# Apply DecisionTreeClassifier

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

# Binary

Using only hosts from **2** subnets

In [6]:
dfb = df[df['Label', 'Label', 'unit'].isin(['UVT', 'SKM'])]
print(dfb['Label', 'Label', 'unit'].value_counts())
dfb.head()

UVT    3500
SKM    3246
Name: (Label, Label, unit), dtype: int64

              mean                                                    \
      FlowDuration
                00        01        02        03        04        05
13291    -0.007496 -0.005742 -0.008903 -0.006316 -0.012004 -0.006973
13292    -0.008895 -0.008315 -0.010002 -0.006953 -0.012740 -0.008184
13293    -0.007623 -0.006104 -0.009037 -0.006413 -0.012109 -0.007140
13294    -0.007596 -0.006030 -0.009027 -0.006398 -0.012092 -0.007123
13295    -0.008925 -0.009641 -0.010201 -0.007432 -0.012726 -0.008296

                                                   ...            max  \
                                                   ...          Bytes
             06        07        08        09      ...             19
13291 -0.006919 -0.012518 -0.009461 -0.011721      ...      -0.015274
13292 -0.008276 -0.013226 -0.010829 -0.012773      ...      -0.015291
13293 -0.007082 -0.012616 -0.009489 -0.011722      ...      -0.015289
13294 -0.007039 -0.012571 -0.009517 -0.011771      ...      -0.014638
13295 -0.008540 -0.013556 -0.010859 -0.013467      ...      -0.015291

                                                       Label  \
                                                       Label
             20        21        22        23 anon_net_range
13291 -0.014957 -0.016592 -0.016750 -0.016306             24
13292 -0.014971 -0.016604 -0.016766 -0.016320             24
13293 -0.014950 -0.016603 -0.016765 -0.016319             24
13294 -0.014446 -0.016041 -0.016122 -0.016018             24
13295 -0.014971 -0.016604 -0.016766 -0.016320             24

                                                               \

                                              addr_range unit
13291  a8ce8c3977ebd10bba6849d15645105eed4d5e78006cfb...  SKM
13292  5a5fa9cbb0325b8b154b37dfee873af049c3f7fbad8141...  SKM
13293  0eb624c7b418aec4d9779fe9a69f171a3c452e8a163e96...  SKM
13294  8d2375a96a2a821d927c290ed665767957ffbbdc55e547...  SKM
13295  ceab45b2cd2a4b0f2af9c73236e4fe98f1bcd1ca8b3bff...  SKM

                          Unit_encoding

                  subunit
13291   centrum Slapanice            16
13292   centrum Slapanice            16
13293   centrum Slapanice            16
13294   centrum Slapanice            16
13295   centrum Slapanice            16

[5 rows x 653 columns]

### Cleanup label encoding

In [7]:
le = LabelEncoder()
dfb['Unit_encoding'] = le.fit_transform(dfb['Label', 'Label', 'unit'].astype(str))

/home/smeriga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
dfb.head()

              mean                                                    \
      FlowDuration
                00        01        02        03        04        05
13291    -0.007496 -0.005742 -0.008903 -0.006316 -0.012004 -0.006973
13292    -0.008895 -0.008315 -0.010002 -0.006953 -0.012740 -0.008184
13293    -0.007623 -0.006104 -0.009037 -0.006413 -0.012109 -0.007140
13294    -0.007596 -0.006030 -0.009027 -0.006398 -0.012092 -0.007123
13295    -0.008925 -0.009641 -0.010201 -0.007432 -0.012726 -0.008296

                                                   ...            max  \
                                                   ...          Bytes
             06        07        08        09      ...             19
13291 -0.006919 -0.012518 -0.009461 -0.011721      ...      -0.015274
13292 -0.008276 -0.013226 -0.010829 -0.012773      ...      -0.015291
13293 -0.007082 -0.012616 -0.009489 -0.011722      ...      -0.015289
13294 -0.007039 -0.012571 -0.009517 -0.011771      ...      -0.014638
13295 -0.008540 -0.013556 -0.010859 -0.013467      ...      -0.015291

                                                       Label  \
                                                       Label
             20        21        22        23 anon_net_range
13291 -0.014957 -0.016592 -0.016750 -0.016306             24
13292 -0.014971 -0.016604 -0.016766 -0.016320             24
13293 -0.014950 -0.016603 -0.016765 -0.016319             24
13294 -0.014446 -0.016041 -0.016122 -0.016018             24
13295 -0.014971 -0.016604 -0.016766 -0.016320             24

                                                               \

                                              addr_range unit
13291  a8ce8c3977ebd10bba6849d15645105eed4d5e78006cfb...  SKM
13292  5a5fa9cbb0325b8b154b37dfee873af049c3f7fbad8141...  SKM
13293  0eb624c7b418aec4d9779fe9a69f171a3c452e8a163e96...  SKM
13294  8d2375a96a2a821d927c290ed665767957ffbbdc55e547...  SKM
13295  ceab45b2cd2a4b0f2af9c73236e4fe98f1bcd1ca8b3bff...  SKM

                          Unit_encoding

                  subunit
13291   centrum Slapanice             0
13292   centrum Slapanice             0
13293   centrum Slapanice             0
13294   centrum Slapanice             0
13295   centrum Slapanice             0

[5 rows x 653 columns]

### Dividing dataset into train/test split

In [9]:
x = dfb.drop(['Label', 'Unit_encoding'], level=0, axis=1)
y = dfb['Unit_encoding']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

## Apply DTs classifier

using deafult parameters as shown below

In [10]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [11]:
prediction = dtc.predict(x_test)

## Classifier performance evaluation

In [12]:
print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

           0       0.94      0.91      0.92       660
           1       0.91      0.94      0.93       690

   micro avg       0.93      0.93      0.93      1350
   macro avg       0.93      0.93      0.93      1350
weighted avg       0.93      0.93      0.93      1350

[[599  61]
 [ 39 651]]

# On some groups

In [13]:
groups = ['UVT', 'SKM', 'CEITEC', 'FI', 'PrirF']

In [14]:
dfg = df[df['Label', 'Label', 'unit'].isin(groups)]
print(dfg['Label', 'Label', 'unit'].value_counts())
dfg.head()

UVT       3500
SKM       3246
PrirF     2599
CEITEC    2223
FI        1289
Name: (Label, Label, unit), dtype: int64

          mean                                                              \
  FlowDuration
            00        01        02        03        04        05        06
0    -0.007622 -0.006103 -0.009019 -0.006422 -0.012099 -0.007141 -0.007069
1    -0.009677 -0.011074 -0.010790 -0.008082 -0.013610 -0.009863 -0.009743
2    -0.009484 -0.010427 -0.010896 -0.008080 -0.013609 -0.009918 -0.009838
3    -0.009932 -0.011126 -0.010762 -0.007984 -0.013595 -0.009918 -0.009470
4    -0.007484 -0.005790 -0.008930 -0.006322 -0.012029 -0.007007 -0.006911

                                     ...            max                      \
                                     ...          Bytes
         07        08        09      ...             19        20        21
0 -0.012616 -0.009572 -0.011851      ...      -0.015290 -0.014971 -0.016604
1 -0.014340 -0.011510 -0.014119      ...      -0.015291 -0.014971 -0.016604
2 -0.014320 -0.011545 -0.013922      ...      -0.015291 -0.014971 -0.016604
3 -0.014341 -0.011979 -0.014230      ...      -0.015291 -0.014971 -0.016604
4 -0.012538 -0.009441 -0.011706      ...      -0.015274 -0.014955 -0.016588

                               Label  \
                               Label
         22        23 anon_net_range
0 -0.016766 -0.016320             28
1 -0.016766 -0.016320             28
2 -0.016766 -0.016320             28
3 -0.016766 -0.016320             28
4 -0.016752 -0.016307             26

                                                              \

                                          addr_range    unit
0  ef160f55b36bd48b37f22bc9c48819b1a0259c2dd27ccc...  CEITEC
1  93b8f5a052053b0db4731b671f78b8c5e5817d38d51ba9...  CEITEC
2  ac600c8985d0f198d532737ea9d58db00905c6c6bebb6b...  CEITEC
3  48bab257d30b1c6eaa225275fe60fc5e1dfe61afe54ace...  CEITEC
4  1cd00c373ace404b829e822bf076631b564bf2bc70db82...  CEITEC

                                                     Unit_encoding

                                             subunit
0   frontendy diskovych poli a aplikacni servery ...             0
1   frontendy diskovych poli a aplikacni servery ...             0
2   frontendy diskovych poli a aplikacni servery ...             0
3   frontendy diskovych poli a aplikacni servery ...             0
4                                                CRS             0

[5 rows x 653 columns]

### Cleanup label encoding

In [15]:
le = LabelEncoder()
dfg['Unit_encoding'] = le.fit_transform(dfg['Label', 'Label', 'unit'].astype(str))

/home/smeriga/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
dfg.head()

          mean                                                              \
  FlowDuration
            00        01        02        03        04        05        06
0    -0.007622 -0.006103 -0.009019 -0.006422 -0.012099 -0.007141 -0.007069
1    -0.009677 -0.011074 -0.010790 -0.008082 -0.013610 -0.009863 -0.009743
2    -0.009484 -0.010427 -0.010896 -0.008080 -0.013609 -0.009918 -0.009838
3    -0.009932 -0.011126 -0.010762 -0.007984 -0.013595 -0.009918 -0.009470
4    -0.007484 -0.005790 -0.008930 -0.006322 -0.012029 -0.007007 -0.006911

                                     ...            max                      \
                                     ...          Bytes
         07        08        09      ...             19        20        21
0 -0.012616 -0.009572 -0.011851      ...      -0.015290 -0.014971 -0.016604
1 -0.014340 -0.011510 -0.014119      ...      -0.015291 -0.014971 -0.016604
2 -0.014320 -0.011545 -0.013922      ...      -0.015291 -0.014971 -0.016604
3 -0.014341 -0.011979 -0.014230      ...      -0.015291 -0.014971 -0.016604
4 -0.012538 -0.009441 -0.011706      ...      -0.015274 -0.014955 -0.016588

                               Label  \
                               Label
         22        23 anon_net_range
0 -0.016766 -0.016320             28
1 -0.016766 -0.016320             28
2 -0.016766 -0.016320             28
3 -0.016766 -0.016320             28
4 -0.016752 -0.016307             26

                                                              \

                                          addr_range    unit
0  ef160f55b36bd48b37f22bc9c48819b1a0259c2dd27ccc...  CEITEC
1  93b8f5a052053b0db4731b671f78b8c5e5817d38d51ba9...  CEITEC
2  ac600c8985d0f198d532737ea9d58db00905c6c6bebb6b...  CEITEC
3  48bab257d30b1c6eaa225275fe60fc5e1dfe61afe54ace...  CEITEC
4  1cd00c373ace404b829e822bf076631b564bf2bc70db82...  CEITEC

                                                     Unit_encoding

                                             subunit
0   frontendy diskovych poli a aplikacni servery ...             0
1   frontendy diskovych poli a aplikacni servery ...             0
2   frontendy diskovych poli a aplikacni servery ...             0
3   frontendy diskovych poli a aplikacni servery ...             0
4                                                CRS             0

[5 rows x 653 columns]

### Dividing dataset into train/test split

In [17]:
x = dfg.drop(['Label', 'Unit_encoding'], level=0, axis=1)
y = dfg['Unit_encoding']
x.head()

          mean                                                              \
  FlowDuration
            00        01        02        03        04        05        06
0    -0.007622 -0.006103 -0.009019 -0.006422 -0.012099 -0.007141 -0.007069
1    -0.009677 -0.011074 -0.010790 -0.008082 -0.013610 -0.009863 -0.009743
2    -0.009484 -0.010427 -0.010896 -0.008080 -0.013609 -0.009918 -0.009838
3    -0.009932 -0.011126 -0.010762 -0.007984 -0.013595 -0.009918 -0.009470
4    -0.007484 -0.005790 -0.008930 -0.006322 -0.012029 -0.007007 -0.006911

                                   ...          max                      \
                                   ...        Bytes
         07        08        09    ...           14        15        16
0 -0.012616 -0.009572 -0.011851    ...    -0.018135 -0.017941 -0.017531
1 -0.014340 -0.011510 -0.014119    ...    -0.018135 -0.017942 -0.017531
2 -0.014320 -0.011545 -0.013922    ...    -0.018135 -0.017942 -0.017531
3 -0.014341 -0.011979 -0.014230    ...    -0.018135 -0.017942 -0.017531
4 -0.012538 -0.009441 -0.011706    ...    -0.018115 -0.017918 -0.017516



         17        18        19        20        21        22        23
0 -0.017640 -0.015971 -0.015290 -0.014971 -0.016604 -0.016766 -0.016320
1 -0.017641 -0.015971 -0.015291 -0.014971 -0.016604 -0.016766 -0.016320
2 -0.017641 -0.015971 -0.015291 -0.014971 -0.016604 -0.016766 -0.016320
3 -0.017641 -0.015971 -0.015291 -0.014971 -0.016604 -0.016766 -0.016320
4 -0.017627 -0.015957 -0.015274 -0.014955 -0.016588 -0.016752 -0.016307

[5 rows x 648 columns]

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

## Apply DTs classifier

In [19]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [20]:
prediction = dtc.predict(x_test)

## Classifier performance evaluation

In [21]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.86      0.87      0.87       423
           1       0.56      0.56      0.56       272
           2       0.71      0.70      0.71       530
           3       0.87      0.85      0.86       665
           4       0.81      0.83      0.82       682

   micro avg       0.79      0.79      0.79      2572
   macro avg       0.76      0.76      0.76      2572
weighted avg       0.79      0.79      0.79      2572

In [22]:
print(confusion_matrix(y_test,prediction))

[[368   8  26   5  16]
 [ 15 151  49  29  28]
 [ 23  58 371  27  51]
 [  7  27  24 566  41]
 [ 13  25  50  26 568]]

# On all subnets

## Dividing dataset into train/test split

In [23]:
x = df.drop(['Label', 'Unit_encoding'], level=0, axis=1)
y = df['Unit_encoding']
x.head()

          mean                                                              \
  FlowDuration
            00        01        02        03        04        05        06
0    -0.007622 -0.006103 -0.009019 -0.006422 -0.012099 -0.007141 -0.007069
1    -0.009677 -0.011074 -0.010790 -0.008082 -0.013610 -0.009863 -0.009743
2    -0.009484 -0.010427 -0.010896 -0.008080 -0.013609 -0.009918 -0.009838
3    -0.009932 -0.011126 -0.010762 -0.007984 -0.013595 -0.009918 -0.009470
4    -0.007484 -0.005790 -0.008930 -0.006322 -0.012029 -0.007007 -0.006911

                                   ...          max                      \
                                   ...        Bytes
         07        08        09    ...           14        15        16
0 -0.012616 -0.009572 -0.011851    ...    -0.018135 -0.017941 -0.017531
1 -0.014340 -0.011510 -0.014119    ...    -0.018135 -0.017942 -0.017531
2 -0.014320 -0.011545 -0.013922    ...    -0.018135 -0.017942 -0.017531
3 -0.014341 -0.011979 -0.014230    ...    -0.018135 -0.017942 -0.017531
4 -0.012538 -0.009441 -0.011706    ...    -0.018115 -0.017918 -0.017516



         17        18        19        20        21        22        23
0 -0.017640 -0.015971 -0.015290 -0.014971 -0.016604 -0.016766 -0.016320
1 -0.017641 -0.015971 -0.015291 -0.014971 -0.016604 -0.016766 -0.016320
2 -0.017641 -0.015971 -0.015291 -0.014971 -0.016604 -0.016766 -0.016320
3 -0.017641 -0.015971 -0.015291 -0.014971 -0.016604 -0.016766 -0.016320
4 -0.017627 -0.015957 -0.015274 -0.014955 -0.016588 -0.016752 -0.016307

[5 rows x 648 columns]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

## Apply DTs classifier

In [25]:
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [26]:
prediction = dtc.predict(x_test)

## Classifier performance evaluation

In [27]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           0       0.72      0.74      0.73       463
           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         3
           3       0.31      0.32      0.32       119
           4       0.38      0.41      0.39       189
           5       0.50      0.48      0.49       276
           6       0.87      0.83      0.85       213
           8       0.55      0.56      0.56       148
           9       0.46      0.55      0.50        75
          10       0.06      0.08      0.07        13
          11       0.52      0.51      0.51       315
          12       0.35      0.36      0.35       146
          13       0.55      0.51      0.53       119
          14       0.55      0.56      0.55       501
          15       0.24      0.24      0.24        91
          16       0.84      0.82      0.83       644
          17       0.43      0.39      0.41        23
          18       0.75      0.71      0.73        17
          19       0.49      0.45      0.47       138
          20       0.79      0.79      0.79       694
          21       0.08      0.17      0.11        12

   micro avg       0.63      0.63      0.63      4200
   macro avg       0.45      0.45      0.45      4200
weighted avg       0.63      0.63      0.63      4200

/home/smeriga/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [28]:
print(confusion_matrix(y_test,prediction))

[[344   0   0   4   4   7   0   2  25   0  16   5   0  20   0   3   0   0
   27   6   0]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   1   0   0   1   0   0   0   0
    0   1   0]
 [  1   0   0  38  13   6   0   3   0   2  16   6   3  11   8  11   0   0
    0   1   0]
 [  5   0   0  17  77  13   0   9   2   1  21   5   7  19   5   4   1   0
    0   3   0]
 [ 11   0   0   9  10 132   9   6   3   3  12   9   8  26   3  15   2   0
    3  15   0]
 [  0   0   0   1   1  10 176   0   0   0   0   5   0   9   0   2   0   0
    0   8   1]
 [  4   0   0   2   6  11   0  83   2   1   5   4   5   9   2   4   3   0
    2   5   0]
 [ 22   0   0   0   2   1   0   0  41   0   1   0   0   2   0   1   0   0
    5   0   0]
 [  1   0   0   0   1   3   0   0   0   1   1   2   0   1   1   0   0   0
    0   2   0]
 [ 26   0   0   5  17  14   0  11   4   1 160   7   4  29  12   7   0   0
    5  13   0]
 [  4   0   0   5   5   7   4   5   1   1   7  52   4  22   7   8   0   1
    1  12   0]
 [  1   0   0   4   7   9   0   7   0   0   8   1  61   6   1   3   1   0
    2   8   0]
 [ 16   0   1  14  30  19   4  11   4   0  23  28   4 279  16  10   0   1
    6  34   1]
 [  2   0   1   8   9   3   0   1   0   0  10   4   4  17  22   2   0   0
    3   5   0]
 [  5   0   0   5   3  13   2   3   1   3   8   3   7  24   4 529   1   2
    1  20  10]
 [  0   0   0   3   1   0   0   0   0   0   2   1   0   4   1   2   9   0
    0   0   0]
 [  0   0   0   1   1   0   0   1   0   0   0   0   0   0   2   0   0  12
    0   0   0]
 [ 30   0   0   1   7   1   0   4   4   0   8   1   1   4   2   2   2   0
   62   9   0]
 [  7   0   0   4   7  14   7   4   2   4   8  14   2  25   4  23   2   0
   10 547  10]
 [  1   0   0   0   0   0   0   0   0   0   0   0   0   0   1   2   0   0
    0   6   2]]